### PR TITLE
Gbdx 2822 button/nav/header styles

### PR DESCRIPTION
**Pull request by mritzman-dg**
PLEASE DO NOT MERGE JUST YET, would like to add some icons before merging this and testing

This PR adds the following:

- now creating dist/style.css from sass and output.css files
- building dist/style.css and copying examples 
- added support for hot reloading when editing sass styles
- styles and examples for buttons, tabs, and headers

### CODE REVIEW

**Comment by winrox** [comment]
Just getting the chance to check this out @mritzman-dg. Didn't work on first try, so I'm doing `npm i` now. Hopefully that'll do it, but let me know if there's anything else I'll need to do to boot up your branch properly.

**Comment by mritzman-dg** [comment]
thanks @winrox for taking a look, yesterday I pushed some updates to fix the build but if you are still seeing them let me know

**Comment by winrox** [comment]
Well, the examples booted up for me just fine at`localhost:8080` after `npm i && npm start` finished.
All of the new things you added look great to me. :) 
Hard to tell exactly how it's working as a package without publishing and trying to pull in elsewhere, but no red flags for me right now.

**Comment by winrox** [comment]
If you want to let me know once you've published, I can test out the latest build in the hub and let you know if things are working properly.

**Comment by mritzman-dg** [comment]
thanks @winrox, I'm thinking we should first pin the version of the last react-good-input wherever we are referencing it in the hub/react-machine/etc then I'll publish a new version

what do you think?  I can commit those now since I have them ready to go

**Comment by mritzman-dg** [comment]
@winrox, just pinned react-good-input to 2.0.13 in hub and react-machine since that is where we are using those buttons

tried to run `npm run publish` and got this:

```
mritzman@mritzman-mbp:~/Development/react-good-input (GBDX-2822-button-styles) $ npm publish
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> react-good-input@2.0.14 prepublish .
> npm run build & npm run build:es


> react-good-input@2.0.14 build:es /Users/mritzman/Development/react-good-input
> BABEL_ENV=es babel --ignore __tests__ -d ./es src


> react-good-input@2.0.14 build /Users/mritzman/Development/react-good-input
> babel --ignore src/styles -d dist src && npm run build-css

src/examples/button_examples.js -> es/examples/button_examples.js
src/examples/button_examples.js -> dist/examples/button_examples.js
src/examples/checkbox_examples.js -> es/examples/checkbox_examples.js
src/examples/checkbox_examples.js -> dist/examples/checkbox_examples.js
src/examples/header_example.js -> dist/examples/header_example.js
src/examples/header_example.js -> es/examples/header_example.js
src/examples/index.js -> dist/examples/index.js
src/examples/index.js -> es/examples/index.js
src/examples/modal_example.js -> dist/examples/modal_example.js
src/examples/modal_example.js -> es/examples/modal_example.js
src/examples/nav_examples.js -> es/examples/nav_examples.js
src/examples/nav_examples.js -> dist/examples/nav_examples.js
src/examples/radio_buttons_example.js -> dist/examples/radio_buttons_example.js
src/examples/radio_buttons_example.js -> es/examples/radio_buttons_example.js
src/examples/select_examples.js -> es/examples/select_examples.js
src/examples/select_examples.js -> dist/examples/select_examples.js
src/examples/text_area_examples.js -> dist/examples/text_area_examples.js
src/examples/text_area_examples.js -> es/examples/text_area_examples.js
src/examples/text_input_examples.js -> es/examples/text_input_examples.js
src/examples/text_input_examples.js -> dist/examples/text_input_examples.js
src/index.js -> es/index.js
src/index.js -> dist/index.js
src/views/checkbox.js -> es/views/checkbox.js
src/views/checkbox.js -> dist/views/checkbox.js
src/views/login.js -> dist/views/login.js
src/views/login.js -> es/views/login.js
src/views/logo.js -> es/views/logo.js
src/views/logo.js -> dist/views/logo.js
src/views/modal.js -> es/views/modal.js
src/views/modal.js -> dist/views/modal.js
src/views/radio.js -> es/views/radio.js
src/views/radio.js -> dist/views/radio.js
src/views/select.js -> es/views/select.js
src/views/select.js -> dist/views/select.js
src/views/textArea.js -> es/views/textArea.js
src/views/textArea.js -> dist/views/textArea.js
src/views/textInput.js -> es/views/textInput.js
src/views/textInput.js -> dist/views/textInput.js
⸨░░░░░░░░░░░░░░░░░░⸩ ⠙ : info lifecycle react-good-input@2.0.14~prepublish: react-good-input@2.0.14
> react-good-input@2.0.14 build-css /Users/mritzman/Development/react-good-input
> ./node_modules/node-sass/bin/node-sass src/styles/index.scss > public/output.css && cp public/output.css dist/style.css

npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mritzman/.npm/_logs/2018-02-23T18_53_11_170Z-debug.log
mritzman@mritzman-mbp:~/Development/react-good-input (GBDX-2822-button-styles) $ 
```

**Comment by winrox** [comment]
Ok to merge this with master now?

**Comment by mritzman-dg** [comment]
sounds good to me, what do you think @cfloth?

**Comment by winrox** [comment]
We should probably go ahead since already published. If Curtis wants you to tweak something, we should just open another issue I'm thinking. In the future, let's merge first, then publish.

**Pull request merged**
